package com.classora.prices.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PriceFactory {
    private PriceFactory() {
    }

    /*
     * Create a new Price entity, lets the id to be generated by JPA
     */
    public static Price create(Long id, Brand brand, LocalDateTime startDate, LocalDateTime endDate,
            Long priceList,
            Long productId, int priority, BigDecimal price, String currency) {
        return new Price(id, brand, startDate, endDate, priceList, productId, priority, price, currency);
    }
}
